#include "pydx12.h"

PYDX12_IMPORT(LUID);
PYDX12_IMPORT_COM(IDXGIObject);

PYDX12_TYPE(DXGI_ADAPTER_DESC);
PYDX12_WSTRING_GETTER(DXGI_ADAPTER_DESC, Description);
PYDX12_GETTER(DXGI_ADAPTER_DESC, VendorId, UnsignedLong);
PYDX12_GETTER(DXGI_ADAPTER_DESC, DeviceId, UnsignedLong);
PYDX12_GETTER(DXGI_ADAPTER_DESC, SubSysId, UnsignedLong);
PYDX12_GETTER(DXGI_ADAPTER_DESC, Revision, UnsignedLong);
PYDX12_GETTER(DXGI_ADAPTER_DESC, DedicatedVideoMemory, UnsignedLongLong);
PYDX12_GETTER(DXGI_ADAPTER_DESC, DedicatedSystemMemory, UnsignedLongLong);
PYDX12_GETTER(DXGI_ADAPTER_DESC, SharedSystemMemory, UnsignedLongLong);
PYDX12_STRUCT_GETTER(DXGI_ADAPTER_DESC, AdapterLuid, LUID);
PYDX12_GETSETTERS(DXGI_ADAPTER_DESC) = {
	PYDX12_DECLARE_GETTER(DXGI_ADAPTER_DESC, Description),
	PYDX12_DECLARE_GETTER(DXGI_ADAPTER_DESC, VendorId),
	PYDX12_DECLARE_GETTER(DXGI_ADAPTER_DESC, DeviceId),
	PYDX12_DECLARE_GETTER(DXGI_ADAPTER_DESC, SubSysId),
	PYDX12_DECLARE_GETTER(DXGI_ADAPTER_DESC, Revision),
	PYDX12_DECLARE_GETTER(DXGI_ADAPTER_DESC, DedicatedVideoMemory),
	PYDX12_DECLARE_GETTER(DXGI_ADAPTER_DESC, DedicatedSystemMemory),
	PYDX12_DECLARE_GETTER(DXGI_ADAPTER_DESC, SharedSystemMemory),
	PYDX12_DECLARE_GETTER(DXGI_ADAPTER_DESC, AdapterLuid),
	{ NULL }  /* Sentinel */
};

PYDX12_TYPE(DXGI_ADAPTER_DESC1);
PYDX12_WSTRING_GETTER(DXGI_ADAPTER_DESC1, Description);
PYDX12_GETTER(DXGI_ADAPTER_DESC1, VendorId, UnsignedLong);
PYDX12_GETTER(DXGI_ADAPTER_DESC1, DeviceId, UnsignedLong);
PYDX12_GETTER(DXGI_ADAPTER_DESC1, SubSysId, UnsignedLong);
PYDX12_GETTER(DXGI_ADAPTER_DESC1, Revision, UnsignedLong);
PYDX12_GETTER(DXGI_ADAPTER_DESC1, DedicatedVideoMemory, UnsignedLongLong);
PYDX12_GETTER(DXGI_ADAPTER_DESC1, DedicatedSystemMemory, UnsignedLongLong);
PYDX12_GETTER(DXGI_ADAPTER_DESC1, SharedSystemMemory, UnsignedLongLong);
PYDX12_STRUCT_GETTER(DXGI_ADAPTER_DESC1, AdapterLuid, LUID);
PYDX12_GETTER(DXGI_ADAPTER_DESC1, Flags, UnsignedLong);
PYDX12_GETSETTERS(DXGI_ADAPTER_DESC1) = {
	PYDX12_DECLARE_GETTER(DXGI_ADAPTER_DESC1, Description),
	PYDX12_DECLARE_GETTER(DXGI_ADAPTER_DESC1, VendorId),
	PYDX12_DECLARE_GETTER(DXGI_ADAPTER_DESC1, DeviceId),
	PYDX12_DECLARE_GETTER(DXGI_ADAPTER_DESC1, SubSysId),
	PYDX12_DECLARE_GETTER(DXGI_ADAPTER_DESC1, Revision),
	PYDX12_DECLARE_GETTER(DXGI_ADAPTER_DESC1, DedicatedVideoMemory),
	PYDX12_DECLARE_GETTER(DXGI_ADAPTER_DESC1, DedicatedSystemMemory),
	PYDX12_DECLARE_GETTER(DXGI_ADAPTER_DESC1, SharedSystemMemory),
	PYDX12_DECLARE_GETTER(DXGI_ADAPTER_DESC1, AdapterLuid),
	PYDX12_DECLARE_GETTER(DXGI_ADAPTER_DESC1, Flags),
	{ NULL }  /* Sentinel */
};

PYDX12_TYPE_COM(IDXGIAdapter);
PYDX12_TYPE_COM(IDXGIAdapter1);

static PyObject* pydx12_IDXGIAdapter_GetDesc(pydx12_COM<IDXGIAdapter>* self)
{
	DXGI_ADAPTER_DESC desc;
	PYDX12_COM_CALL_HRESULT(IDXGIAdapter, GetDesc, &desc);
	return pydx12_instantiate<DXGI_ADAPTER_DESC>(&desc, NULL, NULL);
}

static PyObject* pydx12_IDXGIAdapter1_GetDesc1(pydx12_COM<IDXGIAdapter1>* self)
{
	DXGI_ADAPTER_DESC1 desc;
	PYDX12_COM_CALL_HRESULT(IDXGIAdapter1, GetDesc1, &desc);
	return pydx12_instantiate<DXGI_ADAPTER_DESC1>(&desc, NULL, NULL);
}

PYDX12_METHODS(IDXGIAdapter) = {
	{"GetDesc", (PyCFunction)pydx12_IDXGIAdapter_GetDesc, METH_NOARGS, "Gets a DXGI 1.0 description of an adapter (or video card)"},
	{NULL}  /* Sentinel */
};

PYDX12_METHODS(IDXGIAdapter1) = {
	{"GetDesc1", (PyCFunction)pydx12_IDXGIAdapter1_GetDesc1, METH_NOARGS, "Gets a DXGI 1.1 description of an adapter (or video card)"},
	{NULL}  /* Sentinel */
};

int pydx12_init_adapter(PyObject* m)
{
	pydx12_IDXGIAdapter_Type.tp_methods = pydx12_IDXGIAdapter_methods;
	PYDX12_REGISTER_COM(IDXGIAdapter, IDXGIObject);

	pydx12_IDXGIAdapter_Type.tp_methods = pydx12_IDXGIAdapter1_methods;
	PYDX12_REGISTER_COM(IDXGIAdapter1, IDXGIAdapter);

	PYDX12_REGISTER_STRUCT(DXGI_ADAPTER_DESC);
	PYDX12_REGISTER_STRUCT(DXGI_ADAPTER_DESC1);

	PYDX12_ENUM(DXGI_ADAPTER_FLAG_NONE);
	PYDX12_ENUM(DXGI_ADAPTER_FLAG_REMOTE);
	PYDX12_ENUM(DXGI_ADAPTER_FLAG_SOFTWARE);
	PYDX12_ENUM(DXGI_ADAPTER_FLAG_FORCE_DWORD);

	return 0;
}