#include "pydx12.h"

PYDX12_IMPORT_COM(IDXGIObject);
PYDX12_IMPORT_COM(IDXGIAdapter);
PYDX12_IMPORT_COM(IDXGISwapChain3);
PYDX12_IMPORT_COM(ID3D12CommandQueue);
PYDX12_IMPORT(DXGI_SWAP_CHAIN_DESC1);

PYDX12_IMPORT_HANDLE(Window, HWND);

PYDX12_TYPE_COM(IDXGIFactory);
PYDX12_TYPE_COM(IDXGIFactory1);
PYDX12_TYPE_COM(IDXGIFactory2);
PYDX12_TYPE(DXGI_SAMPLE_DESC);

static PyObject* pydx12_IDXGIFactory_EnumAdapters(pydx12_IDXGIFactory* self)
{
	PyObject* py_adapters = PyList_New(0);
	UINT i = 0;
	IDXGIAdapter* adapter;
	while (self->com_ptr->EnumAdapters(i++, &adapter) != DXGI_ERROR_NOT_FOUND)
	{
		PyObject* py_adapter = pydx12_IDXGIAdapter_instantiate(adapter, false);
		PyList_Append(py_adapters, py_adapter);
		Py_DECREF(py_adapter);
	}
	return py_adapters;
}

static PyObject* pydx12_IDXGIFactory2_CreateSwapChainForHwnd(pydx12_IDXGIFactory2* self, PyObject* args)
{
	PyObject* py_queue;
	PyObject* py_handle;
	PyObject* py_swap_chain_desc1;
	PyObject* py_full_screen_desc = NULL;
	PyObject* py_restrict_to_output = NULL;

	if (!PyArg_ParseTuple(args, "OOO|OO", &py_queue, &py_handle, &py_swap_chain_desc1, &py_full_screen_desc, &py_restrict_to_output))
		return NULL;

	ID3D12CommandQueue* queue = pydx12_ID3D12CommandQueue_check(py_queue);
	if (!queue)
		return PyErr_Format(PyExc_TypeError, "first argument must be a ID3D12CommandQueue");

	PYDX12_ARG_CHECK_HANDLE(Window, HWND, handle);

	DXGI_SWAP_CHAIN_DESC1* swap_chain_desc1 = pydx12_DXGI_SWAP_CHAIN_DESC1_check(py_swap_chain_desc1);
	if (!swap_chain_desc1)
		return PyErr_Format(PyExc_TypeError, "third argument must be a DXGI_SWAP_CHAIN_DESC1");

	if (swap_chain_desc1->BufferCount < 1)
		return PyErr_Format(PyExc_TypeError, "BufferCount in DXGI_SWAP_CHAIN_DESC1 cannot be 0");

	IDXGISwapChain3* swap_chain3 = NULL;
	if (self->com_ptr->CreateSwapChainForHwnd(queue, handle, swap_chain_desc1, NULL, NULL, (IDXGISwapChain1**)&swap_chain3) != S_OK)
	{
		return PyErr_Format(PyExc_ValueError, "unable to create IDXGISwapChain3");
	}

	return pydx12_IDXGISwapChain3_instantiate(swap_chain3, false);
}

PYDX12_METHODS(IDXGIFactory) = {
	{"EnumAdapters", (PyCFunction)pydx12_IDXGIFactory_EnumAdapters, METH_NOARGS, "Returns the list of Adapters in the system"},
	{NULL}  /* Sentinel */
};

PYDX12_METHODS(IDXGIFactory2) = {
	{"CreateSwapChainForHwnd", (PyCFunction)pydx12_IDXGIFactory2_CreateSwapChainForHwnd, METH_VARARGS, "Creates a swap chain that is associated with an HWND handle to the output window for the swap chain"},
	{NULL}  /* Sentinel */
};

PYDX12_GETTER_SETTER(DXGI_SAMPLE_DESC, Count, UnsignedLong, UINT);
PYDX12_GETTER_SETTER(DXGI_SAMPLE_DESC, Quality, UnsignedLong, UINT);

PYDX12_GETSETTERS(DXGI_SAMPLE_DESC) = {
	PYDX12_DECLARE_GETTER_SETTER(DXGI_SAMPLE_DESC, Count),
	PYDX12_DECLARE_GETTER_SETTER(DXGI_SAMPLE_DESC, Quality),
	{NULL}  /* Sentinel */
};

int pydx12_init_dxgi(PyObject* m)
{
	pydx12_IDXGIFactoryType.tp_methods = pydx12_IDXGIFactory_methods;
	PYDX12_REGISTER_COM(IDXGIFactory, IDXGIObject);

	PYDX12_REGISTER_COM(IDXGIFactory1, IDXGIFactory);

	pydx12_IDXGIFactory2Type.tp_methods = pydx12_IDXGIFactory2_methods;
	PYDX12_REGISTER_COM(IDXGIFactory2, IDXGIFactory1);

	PYDX12_REGISTER_STRUCT(DXGI_SAMPLE_DESC);

	PYDX12_ENUM(DXGI_CREATE_FACTORY_DEBUG);

	PYDX12_ENUM(DXGI_FORMAT_UNKNOWN);
	PYDX12_ENUM(DXGI_FORMAT_R32G32B32A32_TYPELESS);
	PYDX12_ENUM(DXGI_FORMAT_R32G32B32A32_FLOAT);
	PYDX12_ENUM(DXGI_FORMAT_R32G32B32A32_UINT);
	PYDX12_ENUM(DXGI_FORMAT_R32G32B32A32_SINT);
	PYDX12_ENUM(DXGI_FORMAT_R32G32B32_TYPELESS);
	PYDX12_ENUM(DXGI_FORMAT_R32G32B32_FLOAT);
	PYDX12_ENUM(DXGI_FORMAT_R32G32B32_UINT);
	PYDX12_ENUM(DXGI_FORMAT_R32G32B32_SINT);
	PYDX12_ENUM(DXGI_FORMAT_R16G16B16A16_TYPELESS);
	PYDX12_ENUM(DXGI_FORMAT_R16G16B16A16_FLOAT);
	PYDX12_ENUM(DXGI_FORMAT_R16G16B16A16_UNORM);
	PYDX12_ENUM(DXGI_FORMAT_R16G16B16A16_UINT);
	PYDX12_ENUM(DXGI_FORMAT_R16G16B16A16_SNORM);
	PYDX12_ENUM(DXGI_FORMAT_R16G16B16A16_SINT);
	PYDX12_ENUM(DXGI_FORMAT_R32G32_TYPELESS);
	PYDX12_ENUM(DXGI_FORMAT_R32G32_FLOAT);
	PYDX12_ENUM(DXGI_FORMAT_R32G32_UINT);
	PYDX12_ENUM(DXGI_FORMAT_R32G32_SINT);
	PYDX12_ENUM(DXGI_FORMAT_R32G8X24_TYPELESS);
	PYDX12_ENUM(DXGI_FORMAT_D32_FLOAT_S8X24_UINT);
	PYDX12_ENUM(DXGI_FORMAT_R32_FLOAT_X8X24_TYPELESS);
	PYDX12_ENUM(DXGI_FORMAT_X32_TYPELESS_G8X24_UINT);
	PYDX12_ENUM(DXGI_FORMAT_R10G10B10A2_TYPELESS);
	PYDX12_ENUM(DXGI_FORMAT_R10G10B10A2_UNORM);
	PYDX12_ENUM(DXGI_FORMAT_R10G10B10A2_UINT);
	PYDX12_ENUM(DXGI_FORMAT_R11G11B10_FLOAT);
	PYDX12_ENUM(DXGI_FORMAT_R8G8B8A8_TYPELESS);
	PYDX12_ENUM(DXGI_FORMAT_R8G8B8A8_UNORM);
	PYDX12_ENUM(DXGI_FORMAT_R8G8B8A8_UNORM_SRGB);
	PYDX12_ENUM(DXGI_FORMAT_R8G8B8A8_UINT);
	PYDX12_ENUM(DXGI_FORMAT_R8G8B8A8_SNORM);
	PYDX12_ENUM(DXGI_FORMAT_R8G8B8A8_SINT);
	PYDX12_ENUM(DXGI_FORMAT_R16G16_TYPELESS);
	PYDX12_ENUM(DXGI_FORMAT_R16G16_FLOAT);
	PYDX12_ENUM(DXGI_FORMAT_R16G16_UNORM);
	PYDX12_ENUM(DXGI_FORMAT_R16G16_UINT);
	PYDX12_ENUM(DXGI_FORMAT_R16G16_SNORM);
	PYDX12_ENUM(DXGI_FORMAT_R16G16_SINT);
	PYDX12_ENUM(DXGI_FORMAT_R32_TYPELESS);
	PYDX12_ENUM(DXGI_FORMAT_D32_FLOAT);
	PYDX12_ENUM(DXGI_FORMAT_R32_FLOAT);
	PYDX12_ENUM(DXGI_FORMAT_R32_UINT);
	PYDX12_ENUM(DXGI_FORMAT_R32_SINT);
	PYDX12_ENUM(DXGI_FORMAT_R24G8_TYPELESS);
	PYDX12_ENUM(DXGI_FORMAT_D24_UNORM_S8_UINT);
	PYDX12_ENUM(DXGI_FORMAT_R24_UNORM_X8_TYPELESS);
	PYDX12_ENUM(DXGI_FORMAT_X24_TYPELESS_G8_UINT);
	PYDX12_ENUM(DXGI_FORMAT_R8G8_TYPELESS);
	PYDX12_ENUM(DXGI_FORMAT_R8G8_UNORM);
	PYDX12_ENUM(DXGI_FORMAT_R8G8_UINT);
	PYDX12_ENUM(DXGI_FORMAT_R8G8_SNORM);
	PYDX12_ENUM(DXGI_FORMAT_R8G8_SINT);
	PYDX12_ENUM(DXGI_FORMAT_R16_TYPELESS);
	PYDX12_ENUM(DXGI_FORMAT_R16_FLOAT);
	PYDX12_ENUM(DXGI_FORMAT_D16_UNORM);
	PYDX12_ENUM(DXGI_FORMAT_R16_UNORM);
	PYDX12_ENUM(DXGI_FORMAT_R16_UINT);
	PYDX12_ENUM(DXGI_FORMAT_R16_SNORM);
	PYDX12_ENUM(DXGI_FORMAT_R16_SINT);
	PYDX12_ENUM(DXGI_FORMAT_R8_TYPELESS);
	PYDX12_ENUM(DXGI_FORMAT_R8_UNORM);
	PYDX12_ENUM(DXGI_FORMAT_R8_UINT);
	PYDX12_ENUM(DXGI_FORMAT_R8_SNORM);
	PYDX12_ENUM(DXGI_FORMAT_R8_SINT);
	PYDX12_ENUM(DXGI_FORMAT_A8_UNORM);
	PYDX12_ENUM(DXGI_FORMAT_R1_UNORM);
	PYDX12_ENUM(DXGI_FORMAT_R9G9B9E5_SHAREDEXP);
	PYDX12_ENUM(DXGI_FORMAT_R8G8_B8G8_UNORM);
	PYDX12_ENUM(DXGI_FORMAT_G8R8_G8B8_UNORM);
	PYDX12_ENUM(DXGI_FORMAT_BC1_TYPELESS);
	PYDX12_ENUM(DXGI_FORMAT_BC1_UNORM);
	PYDX12_ENUM(DXGI_FORMAT_BC1_UNORM_SRGB);
	PYDX12_ENUM(DXGI_FORMAT_BC2_TYPELESS);
	PYDX12_ENUM(DXGI_FORMAT_BC2_UNORM);
	PYDX12_ENUM(DXGI_FORMAT_BC2_UNORM_SRGB);
	PYDX12_ENUM(DXGI_FORMAT_BC3_TYPELESS);
	PYDX12_ENUM(DXGI_FORMAT_BC3_UNORM);
	PYDX12_ENUM(DXGI_FORMAT_BC3_UNORM_SRGB);
	PYDX12_ENUM(DXGI_FORMAT_BC4_TYPELESS);
	PYDX12_ENUM(DXGI_FORMAT_BC4_UNORM);
	PYDX12_ENUM(DXGI_FORMAT_BC4_SNORM);
	PYDX12_ENUM(DXGI_FORMAT_BC5_TYPELESS);
	PYDX12_ENUM(DXGI_FORMAT_BC5_UNORM);
	PYDX12_ENUM(DXGI_FORMAT_BC5_SNORM);
	PYDX12_ENUM(DXGI_FORMAT_B5G6R5_UNORM);
	PYDX12_ENUM(DXGI_FORMAT_B5G5R5A1_UNORM);
	PYDX12_ENUM(DXGI_FORMAT_B8G8R8A8_UNORM);
	PYDX12_ENUM(DXGI_FORMAT_B8G8R8X8_UNORM);
	PYDX12_ENUM(DXGI_FORMAT_R10G10B10_XR_BIAS_A2_UNORM);
	PYDX12_ENUM(DXGI_FORMAT_B8G8R8A8_TYPELESS);
	PYDX12_ENUM(DXGI_FORMAT_B8G8R8A8_UNORM_SRGB);
	PYDX12_ENUM(DXGI_FORMAT_B8G8R8X8_TYPELESS);
	PYDX12_ENUM(DXGI_FORMAT_B8G8R8X8_UNORM_SRGB);
	PYDX12_ENUM(DXGI_FORMAT_BC6H_TYPELESS);
	PYDX12_ENUM(DXGI_FORMAT_BC6H_UF16);
	PYDX12_ENUM(DXGI_FORMAT_BC6H_SF16);
	PYDX12_ENUM(DXGI_FORMAT_BC7_TYPELESS);
	PYDX12_ENUM(DXGI_FORMAT_BC7_UNORM);
	PYDX12_ENUM(DXGI_FORMAT_BC7_UNORM_SRGB);
	PYDX12_ENUM(DXGI_FORMAT_AYUV);
	PYDX12_ENUM(DXGI_FORMAT_Y410);
	PYDX12_ENUM(DXGI_FORMAT_Y416);
	PYDX12_ENUM(DXGI_FORMAT_NV12);
	PYDX12_ENUM(DXGI_FORMAT_P010);
	PYDX12_ENUM(DXGI_FORMAT_P016);
	PYDX12_ENUM(DXGI_FORMAT_420_OPAQUE);
	PYDX12_ENUM(DXGI_FORMAT_YUY2);
	PYDX12_ENUM(DXGI_FORMAT_Y210);
	PYDX12_ENUM(DXGI_FORMAT_Y216);
	PYDX12_ENUM(DXGI_FORMAT_NV11);
	PYDX12_ENUM(DXGI_FORMAT_AI44);
	PYDX12_ENUM(DXGI_FORMAT_IA44);
	PYDX12_ENUM(DXGI_FORMAT_P8);
	PYDX12_ENUM(DXGI_FORMAT_A8P8);
	PYDX12_ENUM(DXGI_FORMAT_B4G4R4A4_UNORM);
	PYDX12_ENUM(DXGI_FORMAT_P208);
	PYDX12_ENUM(DXGI_FORMAT_V208);
	PYDX12_ENUM(DXGI_FORMAT_V408);
	PYDX12_ENUM(DXGI_FORMAT_SAMPLER_FEEDBACK_MIN_MIP_OPAQUE);
	PYDX12_ENUM(DXGI_FORMAT_SAMPLER_FEEDBACK_MIP_REGION_USED_OPAQUE);
	PYDX12_ENUM(DXGI_FORMAT_FORCE_UINT);

	PYDX12_ENUM(DXGI_CPU_ACCESS_NONE);
	PYDX12_ENUM(DXGI_CPU_ACCESS_DYNAMIC);
	PYDX12_ENUM(DXGI_CPU_ACCESS_READ_WRITE);
	PYDX12_ENUM(DXGI_CPU_ACCESS_SCRATCH);
	PYDX12_ENUM(DXGI_CPU_ACCESS_FIELD);
	PYDX12_ENUM(DXGI_USAGE_SHADER_INPUT);
	PYDX12_ENUM(DXGI_USAGE_RENDER_TARGET_OUTPUT);
	PYDX12_ENUM(DXGI_USAGE_BACK_BUFFER);
	PYDX12_ENUM(DXGI_USAGE_SHARED);
	PYDX12_ENUM(DXGI_USAGE_READ_ONLY);
	PYDX12_ENUM(DXGI_USAGE_DISCARD_ON_PRESENT);
	PYDX12_ENUM(DXGI_USAGE_UNORDERED_ACCESS);

	return 0;
}