#include "pydx12.h"

PYDX12_TYPE(XINPUT_GAMEPAD);
PYDX12_GETTER_SETTER(XINPUT_GAMEPAD, wButtons, UnsignedLong, WORD);
PYDX12_GETTER_SETTER(XINPUT_GAMEPAD, bLeftTrigger, UnsignedLong, BYTE);
PYDX12_GETTER_SETTER(XINPUT_GAMEPAD, bRightTrigger, UnsignedLong, BYTE);
PYDX12_GETTER_SETTER(XINPUT_GAMEPAD, sThumbLX, Long, SHORT);
PYDX12_GETTER_SETTER(XINPUT_GAMEPAD, sThumbLY, Long, SHORT);
PYDX12_GETTER_SETTER(XINPUT_GAMEPAD, sThumbRX, Long, SHORT);
PYDX12_GETTER_SETTER(XINPUT_GAMEPAD, sThumbRY, Long, SHORT);
PYDX12_GETSETTERS(XINPUT_GAMEPAD) = {
	PYDX12_DECLARE_GETTER_SETTER(XINPUT_GAMEPAD, wButtons),
	PYDX12_DECLARE_GETTER_SETTER(XINPUT_GAMEPAD, bLeftTrigger),
	PYDX12_DECLARE_GETTER_SETTER(XINPUT_GAMEPAD, bRightTrigger),
	PYDX12_DECLARE_GETTER_SETTER(XINPUT_GAMEPAD, sThumbLX),
	PYDX12_DECLARE_GETTER_SETTER(XINPUT_GAMEPAD, sThumbLY),
	PYDX12_DECLARE_GETTER_SETTER(XINPUT_GAMEPAD, sThumbRX),
	PYDX12_DECLARE_GETTER_SETTER(XINPUT_GAMEPAD, sThumbRY),
	{ NULL }  /* Sentinel */
};

PYDX12_TYPE(XINPUT_STATE);
PYDX12_GETTER_SETTER(XINPUT_STATE, dwPacketNumber, UnsignedLong, DWORD);
PYDX12_STRUCT_GETTER_SETTER(XINPUT_STATE, Gamepad, XINPUT_GAMEPAD);
PYDX12_GETSETTERS(XINPUT_STATE) = {
	PYDX12_DECLARE_GETTER_SETTER(XINPUT_STATE, dwPacketNumber),
	PYDX12_DECLARE_GETTER_SETTER(XINPUT_STATE, Gamepad),
	{ NULL }  /* Sentinel */
};

int pydx12_init_input(PyObject* m)
{
	PYDX12_REGISTER_STRUCT(XINPUT_GAMEPAD);
	PYDX12_REGISTER_STRUCT(XINPUT_STATE);
	return 0;
}